### DISCUSSION TITLE
SvelteKit on Firebase App Hosting

### DISCUSSION THREAD

**Discussion by nela** [FirebaseExtended/firebase-framework-tools#335] [Q&A]
Hey guys,

Judging by the code in `/packages/firebase-frameworks/src
/sveltekit` and [this blog post](https://firebase.blog/posts/2024/05/app-hosting-vs-hosting/), it seems that SvelteKit is supported on App Hosting. However, I have not been able to successfully deploy to App Hosting. I've attempted using `@sveltejs/adapter-node`. 

I've added the following  `.apphosting/bundle.yaml` , and the build runs successfully.

```
version: v1
runConfig:
  runCommand: node build
  minInstances: 0
  maxInstances: 2


metadata:
  adapterPackageName: '@sveltejs/adapter-node'
  adapterVersion: '5.2.12'
  framework: '@sveltejs/kit'
  frameworkVersion: '2.20.2'
```

However, when the container fails with ` failed to launch: path lookup: exec: "PORT=8080": executable file not found in $PATH`. 

Any ideas on what to try next?
